import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "../globals.css";
import Navbar from "@/components/navbar/navbar";
import SocialLinks from "@/components/navbar/social-links";
import MobileNav from "@/components/navbar/mobile-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shadrack Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" transition-colors duration-300">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className=" md:hidden fixed bottom-6">
          <MobileNav />
        </div>
        <SocialLinks />
        {children}
      </body>
    </html>
  );
}
